
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jpype
import org.apache.tika.metadata.filter
import org.apache.tika.metadata.writefilter
import typing



class AccessPermissions:
    PREFIX: typing.ClassVar[str] = ...
    CAN_MODIFY: typing.ClassVar['Property'] = ...
    EXTRACT_CONTENT: typing.ClassVar['Property'] = ...
    EXTRACT_FOR_ACCESSIBILITY: typing.ClassVar['Property'] = ...
    ASSEMBLE_DOCUMENT: typing.ClassVar['Property'] = ...
    FILL_IN_FORM: typing.ClassVar['Property'] = ...
    CAN_MODIFY_ANNOTATIONS: typing.ClassVar['Property'] = ...
    CAN_PRINT: typing.ClassVar['Property'] = ...
    CAN_PRINT_FAITHFUL: typing.ClassVar['Property'] = ...

class ClimateForcast:
    PROGRAM_ID: typing.ClassVar[str] = ...
    COMMAND_LINE: typing.ClassVar[str] = ...
    HISTORY: typing.ClassVar[str] = ...
    TABLE_ID: typing.ClassVar[str] = ...
    INSTITUTION: typing.ClassVar[str] = ...
    SOURCE: typing.ClassVar[str] = ...
    CONTACT: typing.ClassVar[str] = ...
    PROJECT_ID: typing.ClassVar[str] = ...
    CONVENTIONS: typing.ClassVar[str] = ...
    REFERENCES: typing.ClassVar[str] = ...
    ACKNOWLEDGEMENT: typing.ClassVar[str] = ...
    REALIZATION: typing.ClassVar[str] = ...
    EXPERIMENT_ID: typing.ClassVar[str] = ...
    COMMENT: typing.ClassVar[str] = ...
    MODEL_NAME_ENGLISH: typing.ClassVar[str] = ...

class CreativeCommons:
    LICENSE_URL: typing.ClassVar[str] = ...
    LICENSE_LOCATION: typing.ClassVar[str] = ...
    WORK_TYPE: typing.ClassVar[str] = ...

class Database:
    PREFIX: typing.ClassVar[str] = ...
    TABLE_NAME: typing.ClassVar['Property'] = ...
    ROW_COUNT: typing.ClassVar['Property'] = ...
    COLUMN_COUNT: typing.ClassVar['Property'] = ...
    COLUMN_NAME: typing.ClassVar['Property'] = ...

class DublinCore:
    NAMESPACE_URI_DC: typing.ClassVar[str] = ...
    NAMESPACE_URI_DC_TERMS: typing.ClassVar[str] = ...
    PREFIX_DC: typing.ClassVar[str] = ...
    PREFIX_DC_TERMS: typing.ClassVar[str] = ...
    FORMAT: typing.ClassVar['Property'] = ...
    IDENTIFIER: typing.ClassVar['Property'] = ...
    MODIFIED: typing.ClassVar['Property'] = ...
    CONTRIBUTOR: typing.ClassVar['Property'] = ...
    COVERAGE: typing.ClassVar['Property'] = ...
    CREATOR: typing.ClassVar['Property'] = ...
    CREATED: typing.ClassVar['Property'] = ...
    DATE: typing.ClassVar['Property'] = ...
    DESCRIPTION: typing.ClassVar['Property'] = ...
    LANGUAGE: typing.ClassVar['Property'] = ...
    PUBLISHER: typing.ClassVar['Property'] = ...
    RELATION: typing.ClassVar['Property'] = ...
    RIGHTS: typing.ClassVar['Property'] = ...
    SOURCE: typing.ClassVar['Property'] = ...
    SUBJECT: typing.ClassVar['Property'] = ...
    TITLE: typing.ClassVar['Property'] = ...
    TYPE: typing.ClassVar['Property'] = ...

class Epub:
    EPUB_PREFIX: typing.ClassVar[str] = ...
    RENDITION_LAYOUT: typing.ClassVar['Property'] = ...
    VERSION: typing.ClassVar['Property'] = ...

class ExternalProcess:
    PREFIX_EXTERNAL_META: typing.ClassVar[str] = ...
    STD_OUT: typing.ClassVar['Property'] = ...
    STD_ERR: typing.ClassVar['Property'] = ...
    STD_OUT_IS_TRUNCATED: typing.ClassVar['Property'] = ...
    STD_ERR_IS_TRUNCATED: typing.ClassVar['Property'] = ...
    STD_OUT_LENGTH: typing.ClassVar['Property'] = ...
    STD_ERR_LENGTH: typing.ClassVar['Property'] = ...
    EXIT_VALUE: typing.ClassVar['Property'] = ...
    IS_TIMEOUT: typing.ClassVar['Property'] = ...

class FileSystem:
    PREFIX: typing.ClassVar[str] = ...
    CREATED: typing.ClassVar['Property'] = ...
    MODIFIED: typing.ClassVar['Property'] = ...
    ACCESSED: typing.ClassVar['Property'] = ...

class Font:
    PREFIX_FONT_META: typing.ClassVar[str] = ...
    FONT_NAME: typing.ClassVar['Property'] = ...

class Geographic:
    LATITUDE: typing.ClassVar['Property'] = ...
    LONGITUDE: typing.ClassVar['Property'] = ...
    ALTITUDE: typing.ClassVar['Property'] = ...

class HTML:
    PREFIX_HTML_META: typing.ClassVar[str] = ...
    SCRIPT_SOURCE: typing.ClassVar['Property'] = ...

class HttpHeaders:
    CONTENT_ENCODING: typing.ClassVar[str] = ...
    CONTENT_LANGUAGE: typing.ClassVar[str] = ...
    CONTENT_LENGTH: typing.ClassVar[str] = ...
    CONTENT_LOCATION: typing.ClassVar[str] = ...
    CONTENT_DISPOSITION: typing.ClassVar[str] = ...
    CONTENT_MD5: typing.ClassVar[str] = ...
    CONTENT_TYPE: typing.ClassVar[str] = ...
    LOCATION: typing.ClassVar[str] = ...

class IPTC:
    NAMESPACE_URI_IPTC_CORE: typing.ClassVar[str] = ...
    NAMESPACE_URI_IPTC_EXT: typing.ClassVar[str] = ...
    NAMESPACE_URI_PLUS: typing.ClassVar[str] = ...
    PREFIX_IPTC_CORE: typing.ClassVar[str] = ...
    PREFIX_IPTC_EXT: typing.ClassVar[str] = ...
    PREFIX_PLUS: typing.ClassVar[str] = ...
    CITY: typing.ClassVar['Property'] = ...
    COUNTRY: typing.ClassVar['Property'] = ...
    COUNTRY_CODE: typing.ClassVar['Property'] = ...
    DESCRIPTION: typing.ClassVar['Property'] = ...
    HEADLINE: typing.ClassVar['Property'] = ...
    INTELLECTUAL_GENRE: typing.ClassVar['Property'] = ...
    KEYWORDS: typing.ClassVar['Property'] = ...
    PROVINCE_OR_STATE: typing.ClassVar['Property'] = ...
    SCENE_CODE: typing.ClassVar['Property'] = ...
    SUBJECT_CODE: typing.ClassVar['Property'] = ...
    SUBLOCATION: typing.ClassVar['Property'] = ...
    DATE_CREATED: typing.ClassVar['Property'] = ...
    DESCRIPTION_WRITER: typing.ClassVar['Property'] = ...
    INSTRUCTIONS: typing.ClassVar['Property'] = ...
    JOB_ID: typing.ClassVar['Property'] = ...
    TITLE: typing.ClassVar['Property'] = ...
    COPYRIGHT_NOTICE: typing.ClassVar['Property'] = ...
    CREATOR: typing.ClassVar['Property'] = ...
    CREATORS_CONTACT_INFO: typing.ClassVar['Property'] = ...
    CREATORS_JOB_TITLE: typing.ClassVar['Property'] = ...
    CREDIT_LINE: typing.ClassVar['Property'] = ...
    RIGHTS_USAGE_TERMS: typing.ClassVar['Property'] = ...
    SOURCE: typing.ClassVar['Property'] = ...
    CONTACT_INFO_ADDRESS: typing.ClassVar['Property'] = ...
    CONTACT_INFO_CITY: typing.ClassVar['Property'] = ...
    CONTACT_INFO_COUNTRY: typing.ClassVar['Property'] = ...
    CONTACT_INFO_EMAIL: typing.ClassVar['Property'] = ...
    CONTACT_INFO_PHONE: typing.ClassVar['Property'] = ...
    CONTACT_INFO_POSTAL_CODE: typing.ClassVar['Property'] = ...
    CONTACT_INFO_STATE_PROVINCE: typing.ClassVar['Property'] = ...
    CONTACT_INFO_WEB_URL: typing.ClassVar['Property'] = ...
    URGENCY: typing.ClassVar['Property'] = ...
    CATEGORY: typing.ClassVar['Property'] = ...
    SUPPLEMENTAL_CATEGORIES: typing.ClassVar['Property'] = ...
    ADDITIONAL_MODEL_INFO: typing.ClassVar['Property'] = ...
    ARTWORK_OR_OBJECT: typing.ClassVar['Property'] = ...
    ORGANISATION_CODE: typing.ClassVar['Property'] = ...
    CONTROLLED_VOCABULARY_TERM: typing.ClassVar['Property'] = ...
    LOCATION_SHOWN: typing.ClassVar['Property'] = ...
    MODEL_AGE: typing.ClassVar['Property'] = ...
    ORGANISATION_NAME: typing.ClassVar['Property'] = ...
    PERSON: typing.ClassVar['Property'] = ...
    DIGITAL_IMAGE_GUID: typing.ClassVar['Property'] = ...
    DIGITAL_SOURCE_FILE_TYPE: typing.ClassVar['Property'] = ...
    DIGITAL_SOURCE_TYPE: typing.ClassVar['Property'] = ...
    EVENT: typing.ClassVar['Property'] = ...
    IMAGE_REGISTRY_ENTRY: typing.ClassVar['Property'] = ...
    IMAGE_SUPPLIER: typing.ClassVar['Property'] = ...
    IMAGE_SUPPLIER_ID_WRONG_CASE: typing.ClassVar[str] = ...
    IMAGE_SUPPLIER_ID: typing.ClassVar['Property'] = ...
    IMAGE_SUPPLIER_NAME: typing.ClassVar['Property'] = ...
    IMAGE_SUPPLIER_IMAGE_ID: typing.ClassVar['Property'] = ...
    IPTC_LAST_EDITED: typing.ClassVar['Property'] = ...
    LOCATION_CREATED: typing.ClassVar['Property'] = ...
    MAX_AVAIL_HEIGHT: typing.ClassVar['Property'] = ...
    MAX_AVAIL_WIDTH: typing.ClassVar['Property'] = ...
    PLUS_VERSION: typing.ClassVar['Property'] = ...
    COPYRIGHT_OWNER: typing.ClassVar['Property'] = ...
    COPYRIGHT_OWNER_ID_WRONG_CASE: typing.ClassVar[str] = ...
    COPYRIGHT_OWNER_ID: typing.ClassVar['Property'] = ...
    COPYRIGHT_OWNER_NAME: typing.ClassVar['Property'] = ...
    IMAGE_CREATOR: typing.ClassVar['Property'] = ...
    IMAGE_CREATOR_ID_WRONG_CASE: typing.ClassVar[str] = ...
    IMAGE_CREATOR_ID: typing.ClassVar['Property'] = ...
    IMAGE_CREATOR_NAME: typing.ClassVar['Property'] = ...
    LICENSOR: typing.ClassVar['Property'] = ...
    LICENSOR_ID_WRONG_CASE: typing.ClassVar[str] = ...
    LICENSOR_ID: typing.ClassVar['Property'] = ...
    LICENSOR_NAME: typing.ClassVar['Property'] = ...
    LICENSOR_CITY: typing.ClassVar['Property'] = ...
    LICENSOR_COUNTRY: typing.ClassVar['Property'] = ...
    LICENSOR_EMAIL: typing.ClassVar['Property'] = ...
    LICENSOR_EXTENDED_ADDRESS: typing.ClassVar['Property'] = ...
    LICENSOR_POSTAL_CODE: typing.ClassVar['Property'] = ...
    LICENSOR_REGION: typing.ClassVar['Property'] = ...
    LICENSOR_STREET_ADDRESS: typing.ClassVar['Property'] = ...
    LICENSOR_TELEPHONE_1: typing.ClassVar['Property'] = ...
    LICENSOR_TELEPHONE_2: typing.ClassVar['Property'] = ...
    LICENSOR_URL: typing.ClassVar['Property'] = ...
    MINOR_MODEL_AGE_DISCLOSURE: typing.ClassVar['Property'] = ...
    MODEL_RELEASE_ID: typing.ClassVar['Property'] = ...
    MODEL_RELEASE_STATUS: typing.ClassVar['Property'] = ...
    PROPERTY_RELEASE_ID: typing.ClassVar['Property'] = ...
    PROPERTY_RELEASE_STATUS: typing.ClassVar['Property'] = ...
    ARTWORK_OR_OBJECT_DETAIL_COPYRIGHT_NOTICE: typing.ClassVar['Property'] = ...
    ARTWORK_OR_OBJECT_DETAIL_CREATOR: typing.ClassVar['Property'] = ...
    ARTWORK_OR_OBJECT_DETAIL_DATE_CREATED: typing.ClassVar['Property'] = ...
    ARTWORK_OR_OBJECT_DETAIL_SOURCE: typing.ClassVar['Property'] = ...
    ARTWORK_OR_OBJECT_DETAIL_SOURCE_INVENTORY_NUMBER: typing.ClassVar['Property'] = ...
    ARTWORK_OR_OBJECT_DETAIL_TITLE: typing.ClassVar['Property'] = ...
    LOCATION_SHOWN_CITY: typing.ClassVar['Property'] = ...
    LOCATION_SHOWN_COUNTRY_CODE: typing.ClassVar['Property'] = ...
    LOCATION_SHOWN_COUNTRY_NAME: typing.ClassVar['Property'] = ...
    LOCATION_SHOWN_PROVINCE_OR_STATE: typing.ClassVar['Property'] = ...
    LOCATION_SHOWN_SUBLOCATION: typing.ClassVar['Property'] = ...
    LOCATION_SHOWN_WORLD_REGION: typing.ClassVar['Property'] = ...
    LOCATION_CREATED_CITY: typing.ClassVar['Property'] = ...
    LOCATION_CREATED_COUNTRY_CODE: typing.ClassVar['Property'] = ...
    LOCATION_CREATED_COUNTRY_NAME: typing.ClassVar['Property'] = ...
    LOCATION_CREATED_PROVINCE_OR_STATE: typing.ClassVar['Property'] = ...
    LOCATION_CREATED_SUBLOCATION: typing.ClassVar['Property'] = ...
    LOCATION_CREATED_WORLD_REGION: typing.ClassVar['Property'] = ...
    REGISTRY_ENTRY_CREATED_ITEM_ID: typing.ClassVar['Property'] = ...
    REGISTRY_ENTRY_CREATED_ORGANISATION_ID: typing.ClassVar['Property'] = ...
    PROPERTY_GROUP_IPTC_CORE: typing.ClassVar[typing.MutableSequence['Property']] = ...
    PROPERTY_GROUP_IPTC_EXT: typing.ClassVar[typing.MutableSequence['Property']] = ...

class MachineMetadata:
    PREFIX: typing.ClassVar[str] = ...
    ARCHITECTURE_BITS: typing.ClassVar['Property'] = ...
    PLATFORM_SYSV: typing.ClassVar[str] = ...
    PLATFORM_HPUX: typing.ClassVar[str] = ...
    PLATFORM_NETBSD: typing.ClassVar[str] = ...
    PLATFORM_LINUX: typing.ClassVar[str] = ...
    PLATFORM_SOLARIS: typing.ClassVar[str] = ...
    PLATFORM_AIX: typing.ClassVar[str] = ...
    PLATFORM_IRIX: typing.ClassVar[str] = ...
    PLATFORM_FREEBSD: typing.ClassVar[str] = ...
    PLATFORM_TRU64: typing.ClassVar[str] = ...
    PLATFORM_ARM: typing.ClassVar[str] = ...
    PLATFORM_EMBEDDED: typing.ClassVar[str] = ...
    PLATFORM_WINDOWS: typing.ClassVar[str] = ...
    PLATFORM: typing.ClassVar['Property'] = ...
    MACHINE_x86_32: typing.ClassVar[str] = ...
    MACHINE_x86_64: typing.ClassVar[str] = ...
    MACHINE_IA_64: typing.ClassVar[str] = ...
    MACHINE_SPARC: typing.ClassVar[str] = ...
    MACHINE_M68K: typing.ClassVar[str] = ...
    MACHINE_M88K: typing.ClassVar[str] = ...
    MACHINE_MIPS: typing.ClassVar[str] = ...
    MACHINE_PPC: typing.ClassVar[str] = ...
    MACHINE_S370: typing.ClassVar[str] = ...
    MACHINE_S390: typing.ClassVar[str] = ...
    MACHINE_ARM: typing.ClassVar[str] = ...
    MACHINE_VAX: typing.ClassVar[str] = ...
    MACHINE_ALPHA: typing.ClassVar[str] = ...
    MACHINE_EFI: typing.ClassVar[str] = ...
    MACHINE_M32R: typing.ClassVar[str] = ...
    MACHINE_SH3: typing.ClassVar[str] = ...
    MACHINE_SH4: typing.ClassVar[str] = ...
    MACHINE_SH5: typing.ClassVar[str] = ...
    MACHINE_UNKNOWN: typing.ClassVar[str] = ...
    MACHINE_TYPE: typing.ClassVar['Property'] = ...
    ENDIAN: typing.ClassVar['Property'] = ...
    class Endian:
        LITTLE: typing.ClassVar['MachineMetadata.Endian'] = ...
        BIG: typing.ClassVar['MachineMetadata.Endian'] = ...
        def getMSB(self) -> str: ...
        def getName(self) -> str: ...
        def isMSB(self) -> bool: ...

class Message:
    MESSAGE_PREFIX: typing.ClassVar[str] = ...
    MESSAGE_RAW_HEADER_PREFIX: typing.ClassVar[str] = ...
    MESSAGE_RECIPIENT_ADDRESS: typing.ClassVar[str] = ...
    MESSAGE_FROM: typing.ClassVar[str] = ...
    MESSAGE_TO: typing.ClassVar[str] = ...
    MESSAGE_CC: typing.ClassVar[str] = ...
    MESSAGE_BCC: typing.ClassVar[str] = ...
    MULTIPART_SUBTYPE: typing.ClassVar[str] = ...
    MULTIPART_BOUNDARY: typing.ClassVar[str] = ...
    MESSAGE_FROM_NAME: typing.ClassVar['Property'] = ...
    MESSAGE_FROM_EMAIL: typing.ClassVar['Property'] = ...
    MESSAGE_TO_NAME: typing.ClassVar['Property'] = ...
    MESSAGE_TO_DISPLAY_NAME: typing.ClassVar['Property'] = ...
    MESSAGE_TO_EMAIL: typing.ClassVar['Property'] = ...
    MESSAGE_CC_NAME: typing.ClassVar['Property'] = ...
    MESSAGE_CC_DISPLAY_NAME: typing.ClassVar['Property'] = ...
    MESSAGE_CC_EMAIL: typing.ClassVar['Property'] = ...
    MESSAGE_BCC_NAME: typing.ClassVar['Property'] = ...
    MESSAGE_BCC_DISPLAY_NAME: typing.ClassVar['Property'] = ...
    MESSAGE_BCC_EMAIL: typing.ClassVar['Property'] = ...

class Office:
    NAMESPACE_URI_DOC_META: typing.ClassVar[str] = ...
    PREFIX_DOC_META: typing.ClassVar[str] = ...
    USER_DEFINED_METADATA_NAME_PREFIX: typing.ClassVar[str] = ...
    KEYWORDS: typing.ClassVar['Property'] = ...
    INITIAL_AUTHOR: typing.ClassVar['Property'] = ...
    LAST_AUTHOR: typing.ClassVar['Property'] = ...
    AUTHOR: typing.ClassVar['Property'] = ...
    CREATION_DATE: typing.ClassVar['Property'] = ...
    SAVE_DATE: typing.ClassVar['Property'] = ...
    PRINT_DATE: typing.ClassVar['Property'] = ...
    SLIDE_COUNT: typing.ClassVar['Property'] = ...
    PAGE_COUNT: typing.ClassVar['Property'] = ...
    PARAGRAPH_COUNT: typing.ClassVar['Property'] = ...
    LINE_COUNT: typing.ClassVar['Property'] = ...
    WORD_COUNT: typing.ClassVar['Property'] = ...
    CHARACTER_COUNT: typing.ClassVar['Property'] = ...
    CHARACTER_COUNT_WITH_SPACES: typing.ClassVar['Property'] = ...
    TABLE_COUNT: typing.ClassVar['Property'] = ...
    IMAGE_COUNT: typing.ClassVar['Property'] = ...
    OBJECT_COUNT: typing.ClassVar['Property'] = ...
    MAPI_MESSAGE_CLASS: typing.ClassVar['Property'] = ...
    MAPI_SENT_BY_SERVER_TYPE: typing.ClassVar['Property'] = ...
    MAPI_FROM_REPRESENTING_NAME: typing.ClassVar['Property'] = ...
    MAPI_FROM_REPRESENTING_EMAIL: typing.ClassVar['Property'] = ...
    MAPI_MESSAGE_CLIENT_SUBMIT_TIME: typing.ClassVar['Property'] = ...
    PROG_ID: typing.ClassVar['Property'] = ...
    OCX_NAME: typing.ClassVar['Property'] = ...
    MAPI_RECIPIENTS_STRING: typing.ClassVar['Property'] = ...
    MAPI_IMPORTANCE: typing.ClassVar['Property'] = ...
    MAPI_PRIORTY: typing.ClassVar['Property'] = ...
    MAPI_IS_FLAGGED: typing.ClassVar['Property'] = ...

class OfficeOpenXMLCore:
    NAMESPACE_URI: typing.ClassVar[str] = ...
    PREFIX: typing.ClassVar[str] = ...
    CATEGORY: typing.ClassVar['Property'] = ...
    CONTENT_STATUS: typing.ClassVar['Property'] = ...
    LAST_MODIFIED_BY: typing.ClassVar['Property'] = ...
    LAST_PRINTED: typing.ClassVar['Property'] = ...
    REVISION: typing.ClassVar['Property'] = ...
    VERSION: typing.ClassVar['Property'] = ...
    SUBJECT: typing.ClassVar['Property'] = ...

class OfficeOpenXMLExtended:
    NAMESPACE_URI: typing.ClassVar[str] = ...
    WORD_PROCESSING_NAMESPACE_URI: typing.ClassVar[str] = ...
    PREFIX: typing.ClassVar[str] = ...
    WORD_PROCESSING_PREFIX: typing.ClassVar[str] = ...
    SECURITY_NONE: typing.ClassVar[str] = ...
    SECURITY_PASSWORD_PROTECTED: typing.ClassVar[str] = ...
    SECURITY_READ_ONLY_RECOMMENDED: typing.ClassVar[str] = ...
    SECURITY_READ_ONLY_ENFORCED: typing.ClassVar[str] = ...
    SECURITY_LOCKED_FOR_ANNOTATIONS: typing.ClassVar[str] = ...
    SECURITY_UNKNOWN: typing.ClassVar[str] = ...
    TEMPLATE: typing.ClassVar['Property'] = ...
    MANAGER: typing.ClassVar['Property'] = ...
    COMPANY: typing.ClassVar['Property'] = ...
    PRESENTATION_FORMAT: typing.ClassVar['Property'] = ...
    NOTES: typing.ClassVar['Property'] = ...
    TOTAL_TIME: typing.ClassVar['Property'] = ...
    HIDDEN_SLIDES: typing.ClassVar['Property'] = ...
    APPLICATION: typing.ClassVar['Property'] = ...
    APP_VERSION: typing.ClassVar['Property'] = ...
    DOC_SECURITY: typing.ClassVar['Property'] = ...
    DOC_SECURITY_STRING: typing.ClassVar['Property'] = ...
    COMMENTS: typing.ClassVar['Property'] = ...

class PDF:
    PDF_PREFIX: typing.ClassVar[str] = ...
    PDFA_PREFIX: typing.ClassVar[str] = ...
    PDFAID_PREFIX: typing.ClassVar[str] = ...
    EOF_OFFSETS: typing.ClassVar['Property'] = ...
    PDF_DOC_INFO_PREFIX: typing.ClassVar[str] = ...
    PDF_DOC_INFO_CUSTOM_PREFIX: typing.ClassVar[str] = ...
    DOC_INFO_CREATED: typing.ClassVar['Property'] = ...
    DOC_INFO_CREATOR: typing.ClassVar['Property'] = ...
    DOC_INFO_CREATOR_TOOL: typing.ClassVar['Property'] = ...
    DOC_INFO_MODIFICATION_DATE: typing.ClassVar['Property'] = ...
    DOC_INFO_KEY_WORDS: typing.ClassVar['Property'] = ...
    DOC_INFO_PRODUCER: typing.ClassVar['Property'] = ...
    DOC_INFO_SUBJECT: typing.ClassVar['Property'] = ...
    DOC_INFO_TITLE: typing.ClassVar['Property'] = ...
    DOC_INFO_TRAPPED: typing.ClassVar['Property'] = ...
    PDF_VERSION: typing.ClassVar['Property'] = ...
    PDFA_VERSION: typing.ClassVar['Property'] = ...
    PDF_EXTENSION_VERSION: typing.ClassVar['Property'] = ...
    PDFAID_CONFORMANCE: typing.ClassVar['Property'] = ...
    PDFAID_PART: typing.ClassVar['Property'] = ...
    PDFUAID_PART: typing.ClassVar['Property'] = ...
    PDFVT_VERSION: typing.ClassVar['Property'] = ...
    PDFVT_MODIFIED: typing.ClassVar['Property'] = ...
    PDFXID_VERSION: typing.ClassVar['Property'] = ...
    PDFX_VERSION: typing.ClassVar['Property'] = ...
    PDFX_CONFORMANCE: typing.ClassVar['Property'] = ...
    ILLUSTRATOR_TYPE: typing.ClassVar['Property'] = ...
    IS_ENCRYPTED: typing.ClassVar['Property'] = ...
    PRODUCER: typing.ClassVar['Property'] = ...
    ACTION_TRIGGER: typing.ClassVar['Property'] = ...
    ACTION_TRIGGERS: typing.ClassVar['Property'] = ...
    ACTION_TYPES: typing.ClassVar['Property'] = ...
    CHARACTERS_PER_PAGE: typing.ClassVar['Property'] = ...
    UNMAPPED_UNICODE_CHARS_PER_PAGE: typing.ClassVar['Property'] = ...
    TOTAL_UNMAPPED_UNICODE_CHARS: typing.ClassVar['Property'] = ...
    OVERALL_PERCENTAGE_UNMAPPED_UNICODE_CHARS: typing.ClassVar['Property'] = ...
    CONTAINS_DAMAGED_FONT: typing.ClassVar['Property'] = ...
    CONTAINS_NON_EMBEDDED_FONT: typing.ClassVar['Property'] = ...
    HAS_XFA: typing.ClassVar['Property'] = ...
    HAS_XMP: typing.ClassVar['Property'] = ...
    XMP_LOCATION: typing.ClassVar['Property'] = ...
    HAS_ACROFORM_FIELDS: typing.ClassVar['Property'] = ...
    HAS_MARKED_CONTENT: typing.ClassVar['Property'] = ...
    HAS_COLLECTION: typing.ClassVar['Property'] = ...
    EMBEDDED_FILE_DESCRIPTION: typing.ClassVar['Property'] = ...
    EMBEDDED_FILE_ANNOTATION_TYPE: typing.ClassVar['Property'] = ...
    EMBEDDED_FILE_SUBTYPE: typing.ClassVar['Property'] = ...
    HAS_3D: typing.ClassVar['Property'] = ...
    ANNOTATION_TYPES: typing.ClassVar['Property'] = ...
    ANNOTATION_SUBTYPES: typing.ClassVar['Property'] = ...
    NUM_3D_ANNOTATIONS: typing.ClassVar['Property'] = ...
    ASSOCIATED_FILE_RELATIONSHIP: typing.ClassVar['Property'] = ...
    INCREMENTAL_UPDATE_NUMBER: typing.ClassVar['Property'] = ...
    PDF_INCREMENTAL_UPDATE_COUNT: typing.ClassVar['Property'] = ...
    OCR_PAGE_COUNT: typing.ClassVar['Property'] = ...

class PST:
    PST_PREFIX: typing.ClassVar[str] = ...
    PST_FOLDER_PATH: typing.ClassVar['Property'] = ...
    DESCRIPTOR_NODE_ID: typing.ClassVar['Property'] = ...
    IS_VALID: typing.ClassVar['Property'] = ...

class PagedText:
    N_PAGES: typing.ClassVar['Property'] = ...

class Photoshop:
    NAMESPACE_URI_PHOTOSHOP: typing.ClassVar[str] = ...
    PREFIX_PHOTOSHOP: typing.ClassVar[str] = ...
    AUTHORS_POSITION: typing.ClassVar['Property'] = ...
    _COLOR_MODE_CHOICES_INDEXED: typing.ClassVar[typing.MutableSequence[str]] = ...
    COLOR_MODE: typing.ClassVar['Property'] = ...
    CAPTION_WRITER: typing.ClassVar['Property'] = ...
    CATEGORY: typing.ClassVar['Property'] = ...
    CITY: typing.ClassVar['Property'] = ...
    COUNTRY: typing.ClassVar['Property'] = ...
    CREDIT: typing.ClassVar['Property'] = ...
    DATE_CREATED: typing.ClassVar['Property'] = ...
    HEADLINE: typing.ClassVar['Property'] = ...
    INSTRUCTIONS: typing.ClassVar['Property'] = ...
    SOURCE: typing.ClassVar['Property'] = ...
    STATE: typing.ClassVar['Property'] = ...
    SUPPLEMENTAL_CATEGORIES: typing.ClassVar['Property'] = ...
    TRANSMISSION_REFERENCE: typing.ClassVar['Property'] = ...
    URGENCY: typing.ClassVar['Property'] = ...

class Property(java.lang.Comparable['Property']):
    def compareTo(self, property: 'Property') -> int: ...
    @staticmethod
    def composite(property: 'Property', propertyArray: typing.Union[typing.List['Property'], jpype.JArray]) -> 'Property': ...
    def equals(self, object: typing.Any) -> bool: ...
    @staticmethod
    def externalBoolean(string: str) -> 'Property': ...
    @staticmethod
    def externalBooleanSeq(string: str) -> 'Property': ...
    @staticmethod
    def externalClosedChoise(string: str, *string2: str) -> 'Property': ...
    @staticmethod
    def externalDate(string: str) -> 'Property': ...
    @staticmethod
    def externalInteger(string: str) -> 'Property': ...
    @staticmethod
    def externalOpenChoise(string: str, *string2: str) -> 'Property': ...
    @staticmethod
    def externalReal(string: str) -> 'Property': ...
    @staticmethod
    def externalRealSeq(string: str) -> 'Property': ...
    @staticmethod
    def externalText(string: str) -> 'Property': ...
    @staticmethod
    def externalTextBag(string: str) -> 'Property': ...
    @staticmethod
    def get(string: str) -> 'Property': ...
    def getChoices(self) -> java.util.Set[str]: ...
    def getName(self) -> str: ...
    def getPrimaryProperty(self) -> 'Property': ...
    @staticmethod
    def getProperties(string: str) -> java.util.SortedSet['Property']: ...
    @typing.overload
    def getPropertyType(self) -> 'Property.PropertyType': ...
    @typing.overload
    @staticmethod
    def getPropertyType(string: str) -> 'Property.PropertyType': ...
    def getSecondaryExtractProperties(self) -> typing.MutableSequence['Property']: ...
    def getValueType(self) -> 'Property.ValueType': ...
    def hashCode(self) -> int: ...
    @staticmethod
    def internalBoolean(string: str) -> 'Property': ...
    @staticmethod
    def internalClosedChoise(string: str, *string2: str) -> 'Property': ...
    @staticmethod
    def internalDate(string: str) -> 'Property': ...
    @staticmethod
    def internalDateBag(string: str) -> 'Property': ...
    @staticmethod
    def internalInteger(string: str) -> 'Property': ...
    @staticmethod
    def internalIntegerSequence(string: str) -> 'Property': ...
    @staticmethod
    def internalOpenChoise(string: str, *string2: str) -> 'Property': ...
    @staticmethod
    def internalRational(string: str) -> 'Property': ...
    @staticmethod
    def internalReal(string: str) -> 'Property': ...
    @staticmethod
    def internalText(string: str) -> 'Property': ...
    @staticmethod
    def internalTextBag(string: str) -> 'Property': ...
    @staticmethod
    def internalURI(string: str) -> 'Property': ...
    def isExternal(self) -> bool: ...
    def isInternal(self) -> bool: ...
    def isMultiValuePermitted(self) -> bool: ...
    class PropertyType(java.lang.Enum['Property.PropertyType']):
        SIMPLE: typing.ClassVar['Property.PropertyType'] = ...
        STRUCTURE: typing.ClassVar['Property.PropertyType'] = ...
        BAG: typing.ClassVar['Property.PropertyType'] = ...
        SEQ: typing.ClassVar['Property.PropertyType'] = ...
        ALT: typing.ClassVar['Property.PropertyType'] = ...
        COMPOSITE: typing.ClassVar['Property.PropertyType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: str) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'Property.PropertyType': ...
        @staticmethod
        def values() -> typing.MutableSequence['Property.PropertyType']: ...
    class ValueType(java.lang.Enum['Property.ValueType']):
        BOOLEAN: typing.ClassVar['Property.ValueType'] = ...
        OPEN_CHOICE: typing.ClassVar['Property.ValueType'] = ...
        CLOSED_CHOICE: typing.ClassVar['Property.ValueType'] = ...
        DATE: typing.ClassVar['Property.ValueType'] = ...
        INTEGER: typing.ClassVar['Property.ValueType'] = ...
        LOCALE: typing.ClassVar['Property.ValueType'] = ...
        MIME_TYPE: typing.ClassVar['Property.ValueType'] = ...
        PROPER_NAME: typing.ClassVar['Property.ValueType'] = ...
        RATIONAL: typing.ClassVar['Property.ValueType'] = ...
        REAL: typing.ClassVar['Property.ValueType'] = ...
        TEXT: typing.ClassVar['Property.ValueType'] = ...
        URI: typing.ClassVar['Property.ValueType'] = ...
        URL: typing.ClassVar['Property.ValueType'] = ...
        XPATH: typing.ClassVar['Property.ValueType'] = ...
        PROPERTY: typing.ClassVar['Property.ValueType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: str) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'Property.ValueType': ...
        @staticmethod
        def values() -> typing.MutableSequence['Property.ValueType']: ...

class PropertyTypeException(java.lang.IllegalArgumentException):
    @typing.overload
    def __init__(self, string: str): ...
    @typing.overload
    def __init__(self, propertyType: Property.PropertyType): ...
    @typing.overload
    def __init__(self, propertyType: Property.PropertyType, propertyType2: Property.PropertyType): ...
    @typing.overload
    def __init__(self, valueType: Property.ValueType, valueType2: Property.ValueType): ...

class QuattroPro:
    QUATTROPRO_METADATA_NAME_PREFIX: typing.ClassVar[str] = ...
    ID: typing.ClassVar[Property] = ...
    VERSION: typing.ClassVar[Property] = ...
    BUILD: typing.ClassVar[Property] = ...
    LOWEST_VERSION: typing.ClassVar[Property] = ...

class RTFMetadata:
    PREFIX_RTF_META: typing.ClassVar[str] = ...
    RTF_PICT_META_PREFIX: typing.ClassVar[str] = ...
    THUMBNAIL: typing.ClassVar[Property] = ...
    EMB_APP_VERSION: typing.ClassVar[Property] = ...
    EMB_CLASS: typing.ClassVar[Property] = ...
    EMB_TOPIC: typing.ClassVar[Property] = ...
    EMB_ITEM: typing.ClassVar[Property] = ...

class Rendering:
    RENDERING_PREFIX: typing.ClassVar[str] = ...
    RENDERED_BY: typing.ClassVar[Property] = ...
    RENDERED_MS: typing.ClassVar[Property] = ...

class TIFF:
    BITS_PER_SAMPLE: typing.ClassVar[Property] = ...
    IMAGE_LENGTH: typing.ClassVar[Property] = ...
    IMAGE_WIDTH: typing.ClassVar[Property] = ...
    SAMPLES_PER_PIXEL: typing.ClassVar[Property] = ...
    FLASH_FIRED: typing.ClassVar[Property] = ...
    EXPOSURE_TIME: typing.ClassVar[Property] = ...
    F_NUMBER: typing.ClassVar[Property] = ...
    FOCAL_LENGTH: typing.ClassVar[Property] = ...
    ISO_SPEED_RATINGS: typing.ClassVar[Property] = ...
    EQUIPMENT_MAKE: typing.ClassVar[Property] = ...
    EQUIPMENT_MODEL: typing.ClassVar[Property] = ...
    SOFTWARE: typing.ClassVar[Property] = ...
    ORIENTATION: typing.ClassVar[Property] = ...
    RESOLUTION_HORIZONTAL: typing.ClassVar[Property] = ...
    RESOLUTION_VERTICAL: typing.ClassVar[Property] = ...
    RESOLUTION_UNIT: typing.ClassVar[Property] = ...
    ORIGINAL_DATE: typing.ClassVar[Property] = ...
    EXIF_PAGE_COUNT: typing.ClassVar[Property] = ...

class TikaCoreProperties:
    NAMESPACE_PREFIX_DELIMITER: typing.ClassVar[str] = ...
    TIKA_META_PREFIX: typing.ClassVar[str] = ...
    EMBEDDED_DEPTH: typing.ClassVar[Property] = ...
    EMBEDDED_RESOURCE_PATH: typing.ClassVar[Property] = ...
    FINAL_EMBEDDED_RESOURCE_PATH: typing.ClassVar[Property] = ...
    EMBEDDED_ID_PATH: typing.ClassVar[Property] = ...
    EMBEDDED_ID: typing.ClassVar[Property] = ...
    PARSE_TIME_MILLIS: typing.ClassVar[Property] = ...
    TIKA_CONTENT_HANDLER: typing.ClassVar[Property] = ...
    TIKA_CONTENT: typing.ClassVar[Property] = ...
    TIKA_META_EXCEPTION_PREFIX: typing.ClassVar[str] = ...
    TIKA_META_WARN_PREFIX: typing.ClassVar[str] = ...
    CONTAINER_EXCEPTION: typing.ClassVar[Property] = ...
    EMBEDDED_EXCEPTION: typing.ClassVar[Property] = ...
    EMBEDDED_BYTES_EXCEPTION: typing.ClassVar[Property] = ...
    EMBEDDED_WARNING: typing.ClassVar[Property] = ...
    WRITE_LIMIT_REACHED: typing.ClassVar[Property] = ...
    TIKA_META_EXCEPTION_WARNING: typing.ClassVar[Property] = ...
    TRUNCATED_METADATA: typing.ClassVar[Property] = ...
    TIKA_META_EXCEPTION_EMBEDDED_STREAM: typing.ClassVar[Property] = ...
    TIKA_PARSED_BY: typing.ClassVar[Property] = ...
    TIKA_PARSED_BY_FULL_SET: typing.ClassVar[Property] = ...
    TIKA_DETECTED_LANGUAGE: typing.ClassVar[Property] = ...
    TIKA_DETECTED_LANGUAGE_CONFIDENCE: typing.ClassVar[Property] = ...
    TIKA_DETECTED_LANGUAGE_CONFIDENCE_RAW: typing.ClassVar[Property] = ...
    RESOURCE_NAME_KEY: typing.ClassVar[str] = ...
    PROTECTED: typing.ClassVar[str] = ...
    EMBEDDED_RELATIONSHIP_ID: typing.ClassVar[str] = ...
    EMBEDDED_STORAGE_CLASS_ID: typing.ClassVar[str] = ...
    EMBEDDED_RESOURCE_TYPE_KEY: typing.ClassVar[str] = ...
    ORIGINAL_RESOURCE_NAME: typing.ClassVar[Property] = ...
    SOURCE_PATH: typing.ClassVar[Property] = ...
    CONTENT_TYPE_HINT: typing.ClassVar[Property] = ...
    CONTENT_TYPE_USER_OVERRIDE: typing.ClassVar[Property] = ...
    CONTENT_TYPE_PARSER_OVERRIDE: typing.ClassVar[Property] = ...
    FORMAT: typing.ClassVar[Property] = ...
    IDENTIFIER: typing.ClassVar[Property] = ...
    CONTRIBUTOR: typing.ClassVar[Property] = ...
    COVERAGE: typing.ClassVar[Property] = ...
    CREATOR: typing.ClassVar[Property] = ...
    MODIFIER: typing.ClassVar[Property] = ...
    CREATOR_TOOL: typing.ClassVar[Property] = ...
    LANGUAGE: typing.ClassVar[Property] = ...
    PUBLISHER: typing.ClassVar[Property] = ...
    RELATION: typing.ClassVar[Property] = ...
    RIGHTS: typing.ClassVar[Property] = ...
    SOURCE: typing.ClassVar[Property] = ...
    TYPE: typing.ClassVar[Property] = ...
    TITLE: typing.ClassVar[Property] = ...
    DESCRIPTION: typing.ClassVar[Property] = ...
    SUBJECT: typing.ClassVar[Property] = ...
    CREATED: typing.ClassVar[Property] = ...
    MODIFIED: typing.ClassVar[Property] = ...
    PRINT_DATE: typing.ClassVar[Property] = ...
    METADATA_DATE: typing.ClassVar[Property] = ...
    LATITUDE: typing.ClassVar[Property] = ...
    LONGITUDE: typing.ClassVar[Property] = ...
    ALTITUDE: typing.ClassVar[Property] = ...
    RATING: typing.ClassVar[Property] = ...
    NUM_IMAGES: typing.ClassVar[Property] = ...
    COMMENTS: typing.ClassVar[Property] = ...
    EMBEDDED_RESOURCE_TYPE: typing.ClassVar[Property] = ...
    HAS_SIGNATURE: typing.ClassVar[Property] = ...
    SIGNATURE_NAME: typing.ClassVar[Property] = ...
    SIGNATURE_DATE: typing.ClassVar[Property] = ...
    SIGNATURE_LOCATION: typing.ClassVar[Property] = ...
    SIGNATURE_REASON: typing.ClassVar[Property] = ...
    SIGNATURE_FILTER: typing.ClassVar[Property] = ...
    SIGNATURE_CONTACT_INFO: typing.ClassVar[Property] = ...
    IS_ENCRYPTED: typing.ClassVar[Property] = ...
    DETECTED_ENCODING: typing.ClassVar[Property] = ...
    ENCODING_DETECTOR: typing.ClassVar[Property] = ...
    VERSION_COUNT: typing.ClassVar[Property] = ...
    VERSION_NUMBER: typing.ClassVar[Property] = ...
    PIPES_RESULT: typing.ClassVar[Property] = ...
    class EmbeddedResourceType(java.lang.Enum['TikaCoreProperties.EmbeddedResourceType']):
        INLINE: typing.ClassVar['TikaCoreProperties.EmbeddedResourceType'] = ...
        ATTACHMENT: typing.ClassVar['TikaCoreProperties.EmbeddedResourceType'] = ...
        MACRO: typing.ClassVar['TikaCoreProperties.EmbeddedResourceType'] = ...
        METADATA: typing.ClassVar['TikaCoreProperties.EmbeddedResourceType'] = ...
        FONT: typing.ClassVar['TikaCoreProperties.EmbeddedResourceType'] = ...
        THUMBNAIL: typing.ClassVar['TikaCoreProperties.EmbeddedResourceType'] = ...
        RENDERING: typing.ClassVar['TikaCoreProperties.EmbeddedResourceType'] = ...
        VERSION: typing.ClassVar['TikaCoreProperties.EmbeddedResourceType'] = ...
        ALTERNATE_FORMAT_CHUNK: typing.ClassVar['TikaCoreProperties.EmbeddedResourceType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: str) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: str) -> 'TikaCoreProperties.EmbeddedResourceType': ...
        @staticmethod
        def values() -> typing.MutableSequence['TikaCoreProperties.EmbeddedResourceType']: ...

class TikaMimeKeys:
    TIKA_MIME_FILE: typing.ClassVar[str] = ...
    MIME_TYPE_MAGIC: typing.ClassVar[str] = ...

class TikaPagedText:
    TIKA_PAGED_TEXT_PREFIX: typing.ClassVar[str] = ...
    PAGE_NUMBER: typing.ClassVar[Property] = ...
    PAGE_ROTATION: typing.ClassVar[Property] = ...

class WARC:
    PREFIX: typing.ClassVar[str] = ...
    WARC_WARNING: typing.ClassVar[Property] = ...
    WARC_RECORD_CONTENT_TYPE: typing.ClassVar[Property] = ...
    WARC_PAYLOAD_CONTENT_TYPE: typing.ClassVar[Property] = ...
    WARC_RECORD_ID: typing.ClassVar[Property] = ...

class WordPerfect:
    WORDPERFECT_METADATA_NAME_PREFIX: typing.ClassVar[str] = ...
    FILE_SIZE: typing.ClassVar[Property] = ...
    FILE_ID: typing.ClassVar[Property] = ...
    PRODUCT_TYPE: typing.ClassVar[Property] = ...
    FILE_TYPE: typing.ClassVar[Property] = ...
    MAJOR_VERSION: typing.ClassVar[Property] = ...
    MINOR_VERSION: typing.ClassVar[Property] = ...
    ENCRYPTED: typing.ClassVar[Property] = ...

class XMP:
    NAMESPACE_URI: typing.ClassVar[str] = ...
    PREFIX: typing.ClassVar[str] = ...
    PREFIX_: typing.ClassVar[str] = ...
    ABOUT: typing.ClassVar[Property] = ...
    ADVISORY: typing.ClassVar[Property] = ...
    CREATE_DATE: typing.ClassVar[Property] = ...
    CREATOR_TOOL: typing.ClassVar[Property] = ...
    IDENTIFIER: typing.ClassVar[Property] = ...
    LABEL: typing.ClassVar[Property] = ...
    METADATA_DATE: typing.ClassVar[Property] = ...
    MODIFY_DATE: typing.ClassVar[Property] = ...
    NICKNAME: typing.ClassVar[Property] = ...
    RATING: typing.ClassVar[Property] = ...

class XMPDM:
    ABS_PEAK_AUDIO_FILE_PATH: typing.ClassVar[Property] = ...
    ALBUM: typing.ClassVar[Property] = ...
    ALT_TAPE_NAME: typing.ClassVar[Property] = ...
    ARTIST: typing.ClassVar[Property] = ...
    ALBUM_ARTIST: typing.ClassVar[Property] = ...
    AUDIO_MOD_DATE: typing.ClassVar[Property] = ...
    AUDIO_SAMPLE_RATE: typing.ClassVar[Property] = ...
    AUDIO_SAMPLE_TYPE: typing.ClassVar[Property] = ...
    AUDIO_CHANNEL_TYPE: typing.ClassVar[Property] = ...
    AUDIO_COMPRESSOR: typing.ClassVar[Property] = ...
    COMPILATION: typing.ClassVar[Property] = ...
    COMPOSER: typing.ClassVar[Property] = ...
    COPYRIGHT: typing.ClassVar[Property] = ...
    DISC_NUMBER: typing.ClassVar[Property] = ...
    DURATION: typing.ClassVar[Property] = ...
    ENGINEER: typing.ClassVar[Property] = ...
    FILE_DATA_RATE: typing.ClassVar[Property] = ...
    GENRE: typing.ClassVar[Property] = ...
    INSTRUMENT: typing.ClassVar[Property] = ...
    KEY: typing.ClassVar[Property] = ...
    LOG_COMMENT: typing.ClassVar[Property] = ...
    LOOP: typing.ClassVar[Property] = ...
    NUMBER_OF_BEATS: typing.ClassVar[Property] = ...
    METADATA_MOD_DATE: typing.ClassVar[Property] = ...
    PULL_DOWN: typing.ClassVar[Property] = ...
    RELATIVE_PEAK_AUDIO_FILE_PATH: typing.ClassVar[Property] = ...
    RELEASE_DATE: typing.ClassVar[Property] = ...
    SCALE_TYPE: typing.ClassVar[Property] = ...
    SCENE: typing.ClassVar[Property] = ...
    SHOT_DATE: typing.ClassVar[Property] = ...
    SHOT_LOCATION: typing.ClassVar[Property] = ...
    SHOT_NAME: typing.ClassVar[Property] = ...
    SPEAKER_PLACEMENT: typing.ClassVar[Property] = ...
    STRETCH_MODE: typing.ClassVar[Property] = ...
    TAPE_NAME: typing.ClassVar[Property] = ...
    TEMPO: typing.ClassVar[Property] = ...
    TIME_SIGNATURE: typing.ClassVar[Property] = ...
    TRACK_NUMBER: typing.ClassVar[Property] = ...
    VIDEO_ALPHA_MODE: typing.ClassVar[Property] = ...
    VIDEO_ALPHA_UNITY_IS_TRANSPARENT: typing.ClassVar[Property] = ...
    VIDEO_COLOR_SPACE: typing.ClassVar[Property] = ...
    VIDEO_COMPRESSOR: typing.ClassVar[Property] = ...
    VIDEO_FIELD_ORDER: typing.ClassVar[Property] = ...
    VIDEO_FRAME_RATE: typing.ClassVar[Property] = ...
    VIDEO_MOD_DATE: typing.ClassVar[Property] = ...
    VIDEO_PIXEL_DEPTH: typing.ClassVar[Property] = ...
    VIDEO_PIXEL_ASPECT_RATIO: typing.ClassVar[Property] = ...
    class ChannelTypePropertyConverter:
        def __init__(self): ...
        @staticmethod
        def convert(object: typing.Any) -> str: ...
        @staticmethod
        def convertAndSet(metadata: 'Metadata', object: typing.Any) -> None: ...

class XMPIdq:
    NAMESPACE_URI: typing.ClassVar[str] = ...
    PREFIX: typing.ClassVar[str] = ...
    PREFIX_: typing.ClassVar[str] = ...
    SCHEME: typing.ClassVar[Property] = ...

class XMPMM:
    NAMESPACE_URI: typing.ClassVar[str] = ...
    PREFIX: typing.ClassVar[str] = ...
    PREFIX_: typing.ClassVar[str] = ...
    DOCUMENTID: typing.ClassVar[Property] = ...
    INSTANCEID: typing.ClassVar[Property] = ...
    ORIGINAL_DOCUMENTID: typing.ClassVar[Property] = ...
    RENDITION_CLASS: typing.ClassVar[Property] = ...
    RENDITION_PARAMS: typing.ClassVar[Property] = ...
    HISTORY_EVENT_INSTANCEID: typing.ClassVar[Property] = ...
    HISTORY_ACTION: typing.ClassVar[Property] = ...
    HISTORY_WHEN: typing.ClassVar[Property] = ...
    HISTORY_SOFTWARE_AGENT: typing.ClassVar[Property] = ...
    DERIVED_FROM_DOCUMENTID: typing.ClassVar[Property] = ...
    DERIVED_FROM_INSTANCEID: typing.ClassVar[Property] = ...

class XMPRights:
    NAMESPACE_URI_XMP_RIGHTS: typing.ClassVar[str] = ...
    PREFIX_XMP_RIGHTS: typing.ClassVar[str] = ...
    PREFIX_: typing.ClassVar[str] = ...
    CERTIFICATE: typing.ClassVar[Property] = ...
    MARKED: typing.ClassVar[Property] = ...
    OWNER: typing.ClassVar[Property] = ...
    USAGE_TERMS: typing.ClassVar[Property] = ...
    WEB_STATEMENT: typing.ClassVar[Property] = ...

class Metadata(CreativeCommons, Geographic, HttpHeaders, Message, ClimateForcast, TIFF, TikaMimeKeys, java.io.Serializable):
    def __init__(self): ...
    @typing.overload
    def add(self, string: str, string2: str) -> None: ...
    @typing.overload
    def add(self, property: Property, int: int) -> None: ...
    @typing.overload
    def add(self, property: Property, string: str) -> None: ...
    @typing.overload
    def add(self, property: Property, calendar: java.util.Calendar) -> None: ...
    def equals(self, object: typing.Any) -> bool: ...
    @typing.overload
    def get(self, string: str) -> str: ...
    @typing.overload
    def get(self, property: Property) -> str: ...
    def getDate(self, property: Property) -> java.util.Date: ...
    def getInt(self, property: Property) -> int: ...
    def getIntValues(self, property: Property) -> typing.MutableSequence[int]: ...
    def getLongValues(self, property: Property) -> typing.MutableSequence[int]: ...
    @typing.overload
    def getValues(self, string: str) -> typing.MutableSequence[str]: ...
    @typing.overload
    def getValues(self, property: Property) -> typing.MutableSequence[str]: ...
    def hashCode(self) -> int: ...
    @typing.overload
    def isMultiValued(self, string: str) -> bool: ...
    @typing.overload
    def isMultiValued(self, property: Property) -> bool: ...
    def names(self) -> typing.MutableSequence[str]: ...
    def remove(self, string: str) -> None: ...
    @typing.overload
    def set(self, string: str, string2: str) -> None: ...
    @typing.overload
    def set(self, property: Property, boolean: bool) -> None: ...
    @typing.overload
    def set(self, property: Property, double: float) -> None: ...
    @typing.overload
    def set(self, property: Property, int: int) -> None: ...
    @typing.overload
    def set(self, property: Property, string: str) -> None: ...
    @typing.overload
    def set(self, property: Property, stringArray: typing.Union[typing.List[str], jpype.JArray]) -> None: ...
    @typing.overload
    def set(self, property: Property, calendar: java.util.Calendar) -> None: ...
    @typing.overload
    def set(self, property: Property, date: java.util.Date) -> None: ...
    @typing.overload
    def set(self, property: Property, long: int) -> None: ...
    def setAll(self, properties: java.util.Properties) -> None: ...
    def setMetadataWriteFilter(self, metadataWriteFilter: org.apache.tika.metadata.writefilter.MetadataWriteFilter) -> None: ...
    def size(self) -> int: ...
    def toString(self) -> str: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("org.apache.tika.metadata")``.

    AccessPermissions: typing.Type[AccessPermissions]
    ClimateForcast: typing.Type[ClimateForcast]
    CreativeCommons: typing.Type[CreativeCommons]
    Database: typing.Type[Database]
    DublinCore: typing.Type[DublinCore]
    Epub: typing.Type[Epub]
    ExternalProcess: typing.Type[ExternalProcess]
    FileSystem: typing.Type[FileSystem]
    Font: typing.Type[Font]
    Geographic: typing.Type[Geographic]
    HTML: typing.Type[HTML]
    HttpHeaders: typing.Type[HttpHeaders]
    IPTC: typing.Type[IPTC]
    MachineMetadata: typing.Type[MachineMetadata]
    Message: typing.Type[Message]
    Metadata: typing.Type[Metadata]
    Office: typing.Type[Office]
    OfficeOpenXMLCore: typing.Type[OfficeOpenXMLCore]
    OfficeOpenXMLExtended: typing.Type[OfficeOpenXMLExtended]
    PDF: typing.Type[PDF]
    PST: typing.Type[PST]
    PagedText: typing.Type[PagedText]
    Photoshop: typing.Type[Photoshop]
    Property: typing.Type[Property]
    PropertyTypeException: typing.Type[PropertyTypeException]
    QuattroPro: typing.Type[QuattroPro]
    RTFMetadata: typing.Type[RTFMetadata]
    Rendering: typing.Type[Rendering]
    TIFF: typing.Type[TIFF]
    TikaCoreProperties: typing.Type[TikaCoreProperties]
    TikaMimeKeys: typing.Type[TikaMimeKeys]
    TikaPagedText: typing.Type[TikaPagedText]
    WARC: typing.Type[WARC]
    WordPerfect: typing.Type[WordPerfect]
    XMP: typing.Type[XMP]
    XMPDM: typing.Type[XMPDM]
    XMPIdq: typing.Type[XMPIdq]
    XMPMM: typing.Type[XMPMM]
    XMPRights: typing.Type[XMPRights]
    filter: org.apache.tika.metadata.filter.__module_protocol__
    writefilter: org.apache.tika.metadata.writefilter.__module_protocol__
