
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jpype
import org.apache.tika.metadata
import org.apache.tika.mime
import org.apache.tika.parser
import org.apache.tika.parser.microsoft.onenote.fsshttpb
import org.xml.sax
import typing



class Error(java.lang.Enum['Error']):
    OK: typing.ClassVar['Error'] = ...
    SEGV: typing.ClassVar['Error'] = ...
    RESERVED_NONZERO: typing.ClassVar['Error'] = ...
    UNKNOWN_ENUM: typing.ClassVar['Error'] = ...
    INVALID_CONSTANT: typing.ClassVar['Error'] = ...
    STRING_TOO_SHORT: typing.ClassVar['Error'] = ...
    HEX_OUT_OF_RANGE: typing.ClassVar['Error'] = ...
    COMPACT_ID_MISSING: typing.ClassVar['Error'] = ...
    UNKNOWN_GUID: typing.ClassVar['Error'] = ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: str) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: str) -> 'Error': ...
    @staticmethod
    def values() -> typing.MutableSequence['Error']: ...

class ExtendedGUID(java.lang.Comparable['ExtendedGUID']):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, gUID: 'GUID', long: int): ...
    def SerializeToByteList(self) -> java.util.List[int]: ...
    def compareTo(self, extendedGUID: 'ExtendedGUID') -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getExtendedGuidString(self) -> str: ...
    def getGuid(self) -> 'GUID': ...
    def getN(self) -> int: ...
    def hashCode(self) -> int: ...
    @staticmethod
    def nil() -> 'ExtendedGUID': ...
    def setGuid(self, gUID: 'GUID') -> 'ExtendedGUID': ...
    def setN(self, long: int) -> 'ExtendedGUID': ...
    def toString(self) -> str: ...

class GUID(java.lang.Comparable['GUID']):
    def __init__(self, intArray: typing.Union[typing.List[int], jpype.JArray]): ...
    def compareTo(self, gUID: 'GUID') -> int: ...
    def equals(self, object: typing.Any) -> bool: ...
    @staticmethod
    def fromCurlyBraceUTF16Bytes(byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'GUID': ...
    def getGuid(self) -> typing.MutableSequence[int]: ...
    def getGuidString(self) -> str: ...
    def hashCode(self) -> int: ...
    @staticmethod
    def memcmp(intArray: typing.Union[typing.List[int], jpype.JArray], intArray2: typing.Union[typing.List[int], jpype.JArray], int3: int) -> int: ...
    @staticmethod
    def nil() -> 'GUID': ...
    def setGuid(self, intArray: typing.Union[typing.List[int], jpype.JArray]) -> 'GUID': ...
    def toByteArray(self) -> java.util.List[int]: ...
    def toString(self) -> str: ...

class GlobalIdTableEntry3FNDX:
    def __init__(self): ...
    def getEntriesToCopy(self) -> int: ...
    def getIndexCopyFromStart(self) -> int: ...
    def getIndexCopyToStart(self) -> int: ...
    def setEntriesToCopy(self, long: int) -> 'GlobalIdTableEntry3FNDX': ...
    def setIndexCopyFromStart(self, long: int) -> 'GlobalIdTableEntry3FNDX': ...
    def setIndexCopyToStart(self, long: int) -> 'GlobalIdTableEntry3FNDX': ...

class GlobalIdTableEntryFNDX:
    def __init__(self): ...
    def getGuid(self) -> GUID: ...
    def getIndex(self) -> int: ...
    def setGuid(self, gUID: GUID) -> 'GlobalIdTableEntryFNDX': ...
    def setIndex(self, long: int) -> 'GlobalIdTableEntryFNDX': ...

class ObjectSpaceObjectPropSet:
    def __init__(self): ...
    def getBody(self) -> 'PropertySet': ...
    def getContextIDs(self) -> 'ObjectSpaceObjectStreamOfOIDsOSIDsOrContextIDs': ...
    def getOids(self) -> 'ObjectSpaceObjectStreamOfOIDsOSIDsOrContextIDs': ...
    def getOsids(self) -> 'ObjectSpaceObjectStreamOfOIDsOSIDsOrContextIDs': ...
    def setBody(self, propertySet: 'PropertySet') -> 'ObjectSpaceObjectPropSet': ...
    def setContextIDs(self, objectSpaceObjectStreamOfOIDsOSIDsOrContextIDs: 'ObjectSpaceObjectStreamOfOIDsOSIDsOrContextIDs') -> 'ObjectSpaceObjectPropSet': ...
    def setOids(self, objectSpaceObjectStreamOfOIDsOSIDsOrContextIDs: 'ObjectSpaceObjectStreamOfOIDsOSIDsOrContextIDs') -> 'ObjectSpaceObjectPropSet': ...
    def setOsids(self, objectSpaceObjectStreamOfOIDsOSIDsOrContextIDs: 'ObjectSpaceObjectStreamOfOIDsOSIDsOrContextIDs') -> 'ObjectSpaceObjectPropSet': ...

class OneNoteParser(org.apache.tika.parser.Parser):
    ONE_NOTE_PREFIX: typing.ClassVar[str] = ...
    def __init__(self): ...
    def createOneNoteDocumentFromDirectFileResource(self, oneNoteDirectFileResource: 'OneNoteDirectFileResource') -> 'OneNoteDocument': ...
    def getSupportedTypes(self, parseContext: org.apache.tika.parser.ParseContext) -> java.util.Set[org.apache.tika.mime.MediaType]: ...
    def parse(self, inputStream: java.io.InputStream, contentHandler: org.xml.sax.ContentHandler, metadata: org.apache.tika.metadata.Metadata, parseContext: org.apache.tika.parser.ParseContext) -> None: ...

class OneNotePropertyEnum(java.lang.Enum['OneNotePropertyEnum']):
    LayoutTightLayout: typing.ClassVar['OneNotePropertyEnum'] = ...
    PageWidth: typing.ClassVar['OneNotePropertyEnum'] = ...
    PageHeight: typing.ClassVar['OneNotePropertyEnum'] = ...
    OutlineElementChildLevel: typing.ClassVar['OneNotePropertyEnum'] = ...
    Bold: typing.ClassVar['OneNotePropertyEnum'] = ...
    Italic: typing.ClassVar['OneNotePropertyEnum'] = ...
    Underline: typing.ClassVar['OneNotePropertyEnum'] = ...
    Strikethrough: typing.ClassVar['OneNotePropertyEnum'] = ...
    Superscript: typing.ClassVar['OneNotePropertyEnum'] = ...
    Subscript: typing.ClassVar['OneNotePropertyEnum'] = ...
    Font: typing.ClassVar['OneNotePropertyEnum'] = ...
    FontSize: typing.ClassVar['OneNotePropertyEnum'] = ...
    FontColor: typing.ClassVar['OneNotePropertyEnum'] = ...
    Highlight: typing.ClassVar['OneNotePropertyEnum'] = ...
    RgOutlineIndentDistance: typing.ClassVar['OneNotePropertyEnum'] = ...
    BodyTextAlignment: typing.ClassVar['OneNotePropertyEnum'] = ...
    OffsetFromParentHoriz: typing.ClassVar['OneNotePropertyEnum'] = ...
    OffsetFromParentVert: typing.ClassVar['OneNotePropertyEnum'] = ...
    NumberListFormat: typing.ClassVar['OneNotePropertyEnum'] = ...
    LayoutMaxWidth: typing.ClassVar['OneNotePropertyEnum'] = ...
    LayoutMaxHeight: typing.ClassVar['OneNotePropertyEnum'] = ...
    ContentChildNodesOfOutlineElement: typing.ClassVar['OneNotePropertyEnum'] = ...
    ContentChildNodesOfPageManifest: typing.ClassVar['OneNotePropertyEnum'] = ...
    ElementChildNodesOfSection: typing.ClassVar['OneNotePropertyEnum'] = ...
    ElementChildNodesOfPage: typing.ClassVar['OneNotePropertyEnum'] = ...
    ElementChildNodesOfTitle: typing.ClassVar['OneNotePropertyEnum'] = ...
    ElementChildNodesOfOutline: typing.ClassVar['OneNotePropertyEnum'] = ...
    ElementChildNodesOfOutlineElement: typing.ClassVar['OneNotePropertyEnum'] = ...
    ElementChildNodesOfTable: typing.ClassVar['OneNotePropertyEnum'] = ...
    ElementChildNodesOfTableRow: typing.ClassVar['OneNotePropertyEnum'] = ...
    ElementChildNodesOfTableCell: typing.ClassVar['OneNotePropertyEnum'] = ...
    ElementChildNodesOfVersionHistory: typing.ClassVar['OneNotePropertyEnum'] = ...
    EnableHistory: typing.ClassVar['OneNotePropertyEnum'] = ...
    RichEditTextUnicode: typing.ClassVar['OneNotePropertyEnum'] = ...
    ListNodes: typing.ClassVar['OneNotePropertyEnum'] = ...
    NotebookManagementEntityGuid: typing.ClassVar['OneNotePropertyEnum'] = ...
    OutlineElementRTL: typing.ClassVar['OneNotePropertyEnum'] = ...
    LanguageID: typing.ClassVar['OneNotePropertyEnum'] = ...
    LayoutAlignmentInParent: typing.ClassVar['OneNotePropertyEnum'] = ...
    PictureContainer: typing.ClassVar['OneNotePropertyEnum'] = ...
    PageMarginTop: typing.ClassVar['OneNotePropertyEnum'] = ...
    PageMarginBottom: typing.ClassVar['OneNotePropertyEnum'] = ...
    PageMarginLeft: typing.ClassVar['OneNotePropertyEnum'] = ...
    PageMarginRight: typing.ClassVar['OneNotePropertyEnum'] = ...
    ListFont: typing.ClassVar['OneNotePropertyEnum'] = ...
    TopologyCreationTimeStamp: typing.ClassVar['OneNotePropertyEnum'] = ...
    LayoutAlignmentSelf: typing.ClassVar['OneNotePropertyEnum'] = ...
    IsTitleTime: typing.ClassVar['OneNotePropertyEnum'] = ...
    IsBoilerText: typing.ClassVar['OneNotePropertyEnum'] = ...
    PageSize: typing.ClassVar['OneNotePropertyEnum'] = ...
    PortraitPage: typing.ClassVar['OneNotePropertyEnum'] = ...
    EnforceOutlineStructure: typing.ClassVar['OneNotePropertyEnum'] = ...
    EditRootRTL: typing.ClassVar['OneNotePropertyEnum'] = ...
    CannotBeSelected: typing.ClassVar['OneNotePropertyEnum'] = ...
    IsTitleText: typing.ClassVar['OneNotePropertyEnum'] = ...
    IsTitleDate: typing.ClassVar['OneNotePropertyEnum'] = ...
    ListRestart: typing.ClassVar['OneNotePropertyEnum'] = ...
    IsLayoutSizeSetByUser: typing.ClassVar['OneNotePropertyEnum'] = ...
    ListSpacingMu: typing.ClassVar['OneNotePropertyEnum'] = ...
    LayoutOutlineReservedWidth: typing.ClassVar['OneNotePropertyEnum'] = ...
    LayoutResolveChildCollisions: typing.ClassVar['OneNotePropertyEnum'] = ...
    IsReadOnly: typing.ClassVar['OneNotePropertyEnum'] = ...
    LayoutMinimumOutlineWidth: typing.ClassVar['OneNotePropertyEnum'] = ...
    LayoutCollisionPriority: typing.ClassVar['OneNotePropertyEnum'] = ...
    CachedTitleString: typing.ClassVar['OneNotePropertyEnum'] = ...
    DescendantsCannotBeMoved: typing.ClassVar['OneNotePropertyEnum'] = ...
    RichEditTextLangID: typing.ClassVar['OneNotePropertyEnum'] = ...
    LayoutTightAlignment: typing.ClassVar['OneNotePropertyEnum'] = ...
    Charset: typing.ClassVar['OneNotePropertyEnum'] = ...
    CreationTimeStamp: typing.ClassVar['OneNotePropertyEnum'] = ...
    Deletable: typing.ClassVar['OneNotePropertyEnum'] = ...
    ListMSAAIndex: typing.ClassVar['OneNotePropertyEnum'] = ...
    IsBackground: typing.ClassVar['OneNotePropertyEnum'] = ...
    IRecordMedia: typing.ClassVar['OneNotePropertyEnum'] = ...
    CachedTitleStringFromPage: typing.ClassVar['OneNotePropertyEnum'] = ...
    RowCount: typing.ClassVar['OneNotePropertyEnum'] = ...
    ColumnCount: typing.ClassVar['OneNotePropertyEnum'] = ...
    TableBordersVisible: typing.ClassVar['OneNotePropertyEnum'] = ...
    StructureElementChildNodes: typing.ClassVar['OneNotePropertyEnum'] = ...
    ChildGraphSpaceElementNodes: typing.ClassVar['OneNotePropertyEnum'] = ...
    TableColumnWidths: typing.ClassVar['OneNotePropertyEnum'] = ...
    Author: typing.ClassVar['OneNotePropertyEnum'] = ...
    LastModifiedTimeStamp: typing.ClassVar['OneNotePropertyEnum'] = ...
    AuthorOriginal: typing.ClassVar['OneNotePropertyEnum'] = ...
    AuthorMostRecent: typing.ClassVar['OneNotePropertyEnum'] = ...
    LastModifiedTime: typing.ClassVar['OneNotePropertyEnum'] = ...
    IsConflictPage: typing.ClassVar['OneNotePropertyEnum'] = ...
    TableColumnsLocked: typing.ClassVar['OneNotePropertyEnum'] = ...
    SchemaRevisionInOrderToRead: typing.ClassVar['OneNotePropertyEnum'] = ...
    IsConflictObjectForRender: typing.ClassVar['OneNotePropertyEnum'] = ...
    EmbeddedFileContainer: typing.ClassVar['OneNotePropertyEnum'] = ...
    EmbeddedFileName: typing.ClassVar['OneNotePropertyEnum'] = ...
    SourceFilepath: typing.ClassVar['OneNotePropertyEnum'] = ...
    ConflictingUserName: typing.ClassVar['OneNotePropertyEnum'] = ...
    ImageFilename: typing.ClassVar['OneNotePropertyEnum'] = ...
    IsConflictObjectForSelection: typing.ClassVar['OneNotePropertyEnum'] = ...
    PageLevel: typing.ClassVar['OneNotePropertyEnum'] = ...
    TextRunIndex: typing.ClassVar['OneNotePropertyEnum'] = ...
    TextRunFormatting: typing.ClassVar['OneNotePropertyEnum'] = ...
    Hyperlink: typing.ClassVar['OneNotePropertyEnum'] = ...
    UnderlineType: typing.ClassVar['OneNotePropertyEnum'] = ...
    Hidden: typing.ClassVar['OneNotePropertyEnum'] = ...
    HyperlinkProtected: typing.ClassVar['OneNotePropertyEnum'] = ...
    TextRunIsEmbeddedObject: typing.ClassVar['OneNotePropertyEnum'] = ...
    ImageAltText: typing.ClassVar['OneNotePropertyEnum'] = ...
    MathFormatting: typing.ClassVar['OneNotePropertyEnum'] = ...
    ParagraphStyle: typing.ClassVar['OneNotePropertyEnum'] = ...
    ParagraphSpaceBefore: typing.ClassVar['OneNotePropertyEnum'] = ...
    ParagraphSpaceAfter: typing.ClassVar['OneNotePropertyEnum'] = ...
    ParagraphLineSpacingExact: typing.ClassVar['OneNotePropertyEnum'] = ...
    MetaDataObjectsAboveGraphSpace: typing.ClassVar['OneNotePropertyEnum'] = ...
    TextRunDataObject: typing.ClassVar['OneNotePropertyEnum'] = ...
    TextRunData: typing.ClassVar['OneNotePropertyEnum'] = ...
    ParagraphStyleId: typing.ClassVar['OneNotePropertyEnum'] = ...
    HasVersionPages: typing.ClassVar['OneNotePropertyEnum'] = ...
    ActionItemType: typing.ClassVar['OneNotePropertyEnum'] = ...
    NoteTagShape: typing.ClassVar['OneNotePropertyEnum'] = ...
    NoteTagHighlightColor: typing.ClassVar['OneNotePropertyEnum'] = ...
    NoteTagTextColor: typing.ClassVar['OneNotePropertyEnum'] = ...
    NoteTagPropertyStatus: typing.ClassVar['OneNotePropertyEnum'] = ...
    NoteTagLabel: typing.ClassVar['OneNotePropertyEnum'] = ...
    NoteTagCreated: typing.ClassVar['OneNotePropertyEnum'] = ...
    NoteTagCompleted: typing.ClassVar['OneNotePropertyEnum'] = ...
    NoteTagDefinitionOid: typing.ClassVar['OneNotePropertyEnum'] = ...
    NoteTagStates: typing.ClassVar['OneNotePropertyEnum'] = ...
    ActionItemStatus: typing.ClassVar['OneNotePropertyEnum'] = ...
    ActionItemSchemaVersion: typing.ClassVar['OneNotePropertyEnum'] = ...
    ReadingOrderRTL: typing.ClassVar['OneNotePropertyEnum'] = ...
    ParagraphAlignment: typing.ClassVar['OneNotePropertyEnum'] = ...
    VersionHistoryGraphSpaceContextNodes: typing.ClassVar['OneNotePropertyEnum'] = ...
    DisplayedPageNumber: typing.ClassVar['OneNotePropertyEnum'] = ...
    SectionDisplayName: typing.ClassVar['OneNotePropertyEnum'] = ...
    NextStyle: typing.ClassVar['OneNotePropertyEnum'] = ...
    WebPictureContainer14: typing.ClassVar['OneNotePropertyEnum'] = ...
    ImageUploadState: typing.ClassVar['OneNotePropertyEnum'] = ...
    TextExtendedAscii: typing.ClassVar['OneNotePropertyEnum'] = ...
    PictureWidth: typing.ClassVar['OneNotePropertyEnum'] = ...
    PictureHeight: typing.ClassVar['OneNotePropertyEnum'] = ...
    PageMarginOriginX: typing.ClassVar['OneNotePropertyEnum'] = ...
    PageMarginOriginY: typing.ClassVar['OneNotePropertyEnum'] = ...
    WzHyperlinkUrl: typing.ClassVar['OneNotePropertyEnum'] = ...
    TaskTagDueDate: typing.ClassVar['OneNotePropertyEnum'] = ...
    NotebookElementOrderingID: typing.ClassVar['OneNotePropertyEnum'] = ...
    Unknown: typing.ClassVar['OneNotePropertyEnum'] = ...
    @staticmethod
    def getInlineBool(oneNotePropertyEnum: 'OneNotePropertyEnum') -> bool: ...
    @staticmethod
    def getType(oneNotePropertyEnum: 'OneNotePropertyEnum') -> int: ...
    @staticmethod
    def of(long: int) -> 'OneNotePropertyEnum': ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: str) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: str) -> 'OneNotePropertyEnum': ...
    @staticmethod
    def values() -> typing.MutableSequence['OneNotePropertyEnum']: ...

class OneNoteTreeWalkerOptions(java.io.Serializable):
    def __init__(self): ...
    def getUtf16PropertiesToPrint(self) -> java.util.Set[OneNotePropertyEnum]: ...
    def isCrawlAllFileNodesFromRoot(self) -> bool: ...
    def isOnlyLatestRevision(self) -> bool: ...
    def setCrawlAllFileNodesFromRoot(self, boolean: bool) -> 'OneNoteTreeWalkerOptions': ...
    def setOnlyLatestRevision(self, boolean: bool) -> 'OneNoteTreeWalkerOptions': ...
    def setUtf16PropertiesToPrint(self, set: java.util.Set[OneNotePropertyEnum]) -> 'OneNoteTreeWalkerOptions': ...

class ObjectSpaceObjectStreamOfOIDsOSIDsOrContextIDs: ...

class OneNoteDirectFileResource: ...

class OneNoteDocument: ...

class PropertySet: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("org.apache.tika.parser.microsoft.onenote")``.

    Error: typing.Type[Error]
    ExtendedGUID: typing.Type[ExtendedGUID]
    GUID: typing.Type[GUID]
    GlobalIdTableEntry3FNDX: typing.Type[GlobalIdTableEntry3FNDX]
    GlobalIdTableEntryFNDX: typing.Type[GlobalIdTableEntryFNDX]
    ObjectSpaceObjectPropSet: typing.Type[ObjectSpaceObjectPropSet]
    ObjectSpaceObjectStreamOfOIDsOSIDsOrContextIDs: typing.Type[ObjectSpaceObjectStreamOfOIDsOSIDsOrContextIDs]
    OneNoteDirectFileResource: typing.Type[OneNoteDirectFileResource]
    OneNoteDocument: typing.Type[OneNoteDocument]
    OneNoteParser: typing.Type[OneNoteParser]
    OneNotePropertyEnum: typing.Type[OneNotePropertyEnum]
    OneNoteTreeWalkerOptions: typing.Type[OneNoteTreeWalkerOptions]
    PropertySet: typing.Type[PropertySet]
    fsshttpb: org.apache.tika.parser.microsoft.onenote.fsshttpb.__module_protocol__
