
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.util
import org.apache.tika.metadata
import org.apache.tika.mime
import org.apache.tika.parser
import org.xml.sax
import typing



class ListDescriptor:
    NUMBER_TYPE_BULLET: typing.ClassVar[int] = ...
    id: int = ...
    templateID: int = ...
    isStyle: bool = ...
    numberType: typing.MutableSequence[int] = ...
    def __init__(self): ...
    def isUnordered(self, int: int) -> bool: ...

class RTFParser(org.apache.tika.parser.Parser):
    def __init__(self): ...
    def getMemoryLimitInKb(self) -> int: ...
    def getSupportedTypes(self, parseContext: org.apache.tika.parser.ParseContext) -> java.util.Set[org.apache.tika.mime.MediaType]: ...
    def parse(self, inputStream: java.io.InputStream, contentHandler: org.xml.sax.ContentHandler, metadata: org.apache.tika.metadata.Metadata, parseContext: org.apache.tika.parser.ParseContext) -> None: ...
    def setMemoryLimitInKb(self, int: int) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("org.apache.tika.parser.microsoft.rtf")``.

    ListDescriptor: typing.Type[ListDescriptor]
    RTFParser: typing.Type[RTFParser]
