
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.util
import org.apache.commons.compress.archivers.zip
import org.apache.tika.detect
import org.apache.tika.detect.zip
import org.apache.tika.io
import org.apache.tika.metadata
import org.apache.tika.mime
import typing



class BPListDetector(org.apache.tika.detect.Detector):
    MEMGRAPH: typing.ClassVar[org.apache.tika.mime.MediaType] = ...
    WEBARCHIVE: typing.ClassVar[org.apache.tika.mime.MediaType] = ...
    PLIST: typing.ClassVar[org.apache.tika.mime.MediaType] = ...
    ITUNES: typing.ClassVar[org.apache.tika.mime.MediaType] = ...
    BMEMGRAPH: typing.ClassVar[org.apache.tika.mime.MediaType] = ...
    BWEBARCHIVE: typing.ClassVar[org.apache.tika.mime.MediaType] = ...
    BPLIST: typing.ClassVar[org.apache.tika.mime.MediaType] = ...
    BITUNES: typing.ClassVar[org.apache.tika.mime.MediaType] = ...
    def __init__(self): ...
    def detect(self, inputStream: java.io.InputStream, metadata: org.apache.tika.metadata.Metadata) -> org.apache.tika.mime.MediaType: ...
    @staticmethod
    def detectOnKeys(set: java.util.Set[str]) -> org.apache.tika.mime.MediaType: ...
    @staticmethod
    def detectXMLOnKeys(set: java.util.Set[str]) -> org.apache.tika.mime.MediaType: ...

class IWorkDetector(org.apache.tika.detect.zip.ZipContainerDetector):
    def __init__(self): ...
    def detect(self, zipFile: org.apache.commons.compress.archivers.zip.ZipFile, tikaInputStream: org.apache.tika.io.TikaInputStream) -> org.apache.tika.mime.MediaType: ...
    def streamingDetectFinal(self, streamingDetectContext: org.apache.tika.detect.zip.StreamingDetectContext) -> org.apache.tika.mime.MediaType: ...
    def streamingDetectUpdate(self, zipArchiveEntry: org.apache.commons.compress.archivers.zip.ZipArchiveEntry, inputStream: java.io.InputStream, streamingDetectContext: org.apache.tika.detect.zip.StreamingDetectContext) -> org.apache.tika.mime.MediaType: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("org.apache.tika.detect.apple")``.

    BPListDetector: typing.Type[BPListDetector]
    IWorkDetector: typing.Type[IWorkDetector]
