name: Test Coverage
on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["master"]

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies with uv
        run: |
          uv sync

      - name: Run tests and generate coverage
        run: |
          uv run pytest -m 'not benchmark' --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=tika test/ | tee pytest-coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
