name: Update Coverage Badge
on:
  push:
    branches: ["master"]

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  update-coverage-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies with uv
        run: |
          uv sync

      - name: Run tests and generate coverage
        run: |
          uv run pytest -m 'not benchmark' --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=tika test/ | tee pytest-coverage.txt

      - name: Pytest coverage comment
        id: coverage-comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          hide-comment: true
          pytest-coverage-path: ./pytest-coverage.txt

      - name: Update README with Coverage Badge
        run: |
          sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n${{ steps.coverage-comment.outputs.coverageHtml }}\n<!-- Pytest Coverage Comment:End -->' ./README.md

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          message: "Update coverage badge"
          github_token: ${{ secrets.GITHUB_TOKEN }}
